export interface Material{
    Negocio?: any;
    Categoria_Gas?: any;
    Categorias?: any;
    Sub_Categoria?: any;
    Sub_Categoria_2?: any;
    Forma_suministro?: any;
    Etapa?: any;
    Tipo_Gas?: any;
    Modelo?: any;
    Nombre?: any;
    Texto_Codigo?: any;
    Codigo: any;
    Texto_Codigo_2?: any;
    Codigo_Purga?: any;
    Texto_Codigo_3?: any;
    Codigo_3?: any;
    Venta_Directa?: any;
    Gas?: any;
    Texto_Presion_1?: any;
    Presion_1?: any;
    Unidades_Presion_1?: any;
    Texto_Presion_2?: any;
    Presion_2?: any; 
    Unidades_Presion_2?: any;
    Texto_Caudal_N?: any;
    Caudal_N2?: any;
    Unidades_Caudal_N2?: any;
    Material_Cuerpo?: any;
    Regulador_Tipo?: any;
    Material_Cierre?: any;
    Material_Junta?: any;
    Material_Asiento?: any;
    Material_Fuelle?: any;
    MateriaL_Eje?: any;
    Material_Husillo?: any;
    Material_Bola?: any;
    Material_Tubo?: any;
    Orificio?: any;
    Unidades_Orificio?: any;
    Conexion_Entrada?: any;
    Conexion_Salida?: any;
    Tipo_conexion_entrada_Botella?: any;
    Conexion_valvula?: any;
    Conexion_rampa?: any;
    Dist_entre_tomas?: any;
    Unidades_Dist_entre_tomas?: any;
    Dist_entre_soportes?: any;
    Unidades_Dist_entre_soportes?: any;
    Material_colector?: any;
    Diametro_Exterior?: any;
    Unidades_Diametro_Exterior?: any;
    Conexion_Botella?: any;
    Rosca_Espiga?: any;
    Material_Cana?: any;
    Material_Tuerca?: any;
    Campo_de_ajuste?: any;
    Unidades_Campo_de_ajuste?: any;
    Clasificacion_Proteccion?: any;
    Resistencia?: any;
    Unidades_Resistencia?: any;
    Contenedor?: any;
    Unidades_Contenedor?: any;
    Diametro_Contenedor?: any;
    Superficie_Activa?: any;
    Termostato?: any;
    Peso_Pallet?: any;
    Unidades_Peso_Pallet?: any;
    Tamano_Pallet?: any;
    Tiempo_de_inyeccion?: any;
    Unidades_Tiempo_de_inyeccion?: any;
    Tipo_de_Globo?: any;
}

// export interface Material{
//     Negocio?: string;
//     Categoria_Gas?: string;
//     Categorias?: string;
//     Sub_Categoria?: any;
//     Sub_Categoria_2?: any;
//     Forma_suministro?: any;
//     Etapa?: any;
//     Tipo_Gas?: any;
//     Modelo?: string;
//     Nombre?: string;
//     Texto_Codigo?: string;
//     Codigo: number;
//     Texto_Codigo_2?: any;
//     Codigo_Purga?: any;
//     Texto_Codigo_3?: any;
//     Codigo_3?: any;
//     Venta_Directa?: any;
//     Gas?: string;
//     Texto_Presion_1?: string;
//     Presion_1?: any;
//     Unidades_Presion_1?: string;
//     Texto_Presion_2?: string;
//     Presion_2?: any; 
//     Unidades_Presion_2?: string;
//     Texto_Caudal_N?: string;
//     Caudal_N2?: any;
//     Unidades_Caudal_N2?: string;
//     Material_Cuerpo?: string;
//     Regulador_Tipo?: string;
//     Material_Cierre?: any;
//     Material_Junta?: any;
//     Material_Asiento?: any;
//     Material_Fuelle?: any;
//     MateriaL_Eje?: any;
//     Material_Husillo?: any;
//     Material_Bola?: any;
//     Material_Tubo?: any;
//     Orificio?: any;
//     Unidades_Orificio?: any;
//     Conexión_Entrada?: any;
//     Conexión_Salida?: any;
//     Tipo_conexion_entrada_Botella?: any;
//     Conexión_valvula?: any;
//     Conexion_rampa?: any;
//     Dist_entre_tomas?: any;
//     Unidades_Dist_entre_tomas?: any;
//     Dist_entre_soportes?: any;
//     Unidades_Dist_entre_soportes?: any;
//     Material_colector?: any;
//     Diametro_Exterior?: any;
//     Unidades_Diametro_Exterior?: any;
//     Conexión_Botella?: any;
//     Rosca_Espiga?: any;
//     Material_Cana?: any;
//     Material_Tuerca?: any;
//     Campo_de_ajuste?: any;
//     Unidades_Campo_de_ajuste?: any;
//     Clasificacion_Proteccion?: any;
//     Resistencia?: any;
//     Unidades_Resistencia?: any;
//     Contenedor?: any;
//     Unidades_Contenedor?: any;
//     Diametro_Contenedor?: any;
//     Superficie_Activa?: any;
//     Termostato?: any;
//     Peso_Pallet?: any;
//     Unidades_Peso_Pallet?: any;
//     Tamano_Pallet?: any;
//     Tiempo_de_inyeccion?: any;
//     Unidades_Tiempo_de_inyeccion?: any;
//     Tipo_de_Globo?: any;
// }