import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MaterialService {

  private myMaterial : any[]=[
    {
      "Negocio": "Packaged",
      "Categoria de Gas": "Gases Especiales",
      "Categorias": "Paneles Gases Especiales (200 Bar)",
      "Sub-Categoria": null,
      "Sub-Categoria 2": null,
      "Forma de suministro": null,
      "Etapa": null,
      "Tipo de Gas": null,
      "Modelo": "Paneles de regulación IGE-10",
      "Unnamed: 9": null,
      "Nombre": "IGE-10/40/1.5",
      "Texto Codigo": "Cod.",
      "Codigo": 81248,
      "Texto Codigo 2": null,
      "Codigo Purga": null,
      "Texto Codigo 3": null,
      "Codigo 3": null,
      "Venta Directa": null,
      "Gas": "Acetileno y gases omprimidos NO corrosivos.",
      "Texto Presion 1": "Presión Entrada:",
      "Presion 1": 40,
      "Unidades Presion 1": "Bar",
      "Texto Presion 2": "Presión Salida:",
      "Presion 2": "0,2 - 1,5",
      "Unidades Presion 2": "Bar",
      "Texto Caudal (N\")": "Caudal:",
      "Caudal (N2)": 5,
      "Unidades Caudal (N2)": "Nm3/h",
      "Material Cuerpo": "Latón",
      "Regulador Tipo": "Membrana Inoxidable",
      "Material Cierre": "Teflón",
      "Material Junta": "EPDM",
      "Material Asiento": null,
      "Material Fuelle": null,
      "Material Eje": null,
      "Material Husillo": null,
      "Material Bola": null,
      "Material Tubo": null,
      "Orificio": null,
      "Unidades Orificio": null,
      "Conexion Entrada": null,
      "Conexion Salida": null,
      "Tipo conexion entrada Botella": null,
      "Conexion valvula": null,
      "Conexion rampa": null,
      "Dist. entre tomas": null,
      "Unidades Dist. entre tomas": null,
      "Dist. entre soportes": null,
      "Unidades Dist. entre soportes": null,
      "Material colector": null,
      "Diametro Exterior": null,
      "Unidades Diametro Exterior": null,
      "Conexion a Botella": null,
      "Rosca-Espiga": null,
      "Material Caña": null,
      "Material Tuerca": null,
      "Campo de ajuste": null,
      "Unidades Campo de ajuste": null,
      "Clasificacion Proteccion": null,
      "Resistencia": null,
      "Unidades Resistencia": null,
      "Contenedor": null,
      "Unidades Contenedor": null,
      "Diametro Contenedor": null,
      "Superficie Activa": null,
      "Termostato": null,
      "Peso Pallet": null,
      "Unidades Peso Pallet": null,
      "Tamaño Pallet": null,
      "Tiempo de inyeccion": null,
      "Unidades Tiempo de inyeccion": null,
      "Tipo de Globo": null,
      "Unnamed: 72": null,
      "Unnamed: 73": null,
      "Complementos": null,
      "Tipo de Entrada": null,
      "Conexion Entrada.1": null,
      "Conexion Salida.1": null,
      "Conexion Valvula": null,
      "Conexion Rampa": null,
      "Dist. Entre tomas": null,
      "Presion de trabajo": null,
      "Dist. Entre Soportes": null,
      "Diametro Interior": null,
      "Conexion": null,
      "Orificio.1": null,
      "Presion Max.": null,
      "Presion Tarado": null,
      "Campo de Ajuste": null,
      "Longitud cable salida": null,
      "Rango de Presion": null,
      "Proteccion Clasificacion": null,
      "Presion Nominal": null,
      "Peso Pallet.1": null,
      "Tamaño Pallet.1": null,
      "Tiempo de inyección": null,
      "Conexion a botella": null,
      "Naprox de Pallet x 6,35 kg CO2": null,
      "Composicion": null,
      "Tipo de Globo.1": null,
      "Tipo de Conexion": null,
      "Tipo": null,
      "Junta": null,
      "Conexion a Regulador": null,
      "Material Caña ": null,
      "Material Tuerca.1": null,
      "Capacidad geometrica litros": null,
      "Capacidad de gas aprox": null,
      "Peso Total": null
    },
    {
      "Negocio": "Packaged",
      "Categoria de Gas": "Gases Especiales",
      "Categorias": "Paneles Gases Especiales (200 Bar)",
      "Sub-Categoria": null,
      "Sub-Categoria 2": null,
      "Forma de suministro": null,
      "Etapa": null,
      "Tipo de Gas": null,
      "Modelo": "Paneles de regulación IGE-10",
      "Unnamed: 9": null,
      "Nombre": "IGE-10/100/14",
      "Texto Codigo": "Cod.",
      "Codigo": 81265,
      "Texto Codigo 2": null,
      "Codigo Purga": null,
      "Texto Codigo 3": null,
      "Codigo 3": null,
      "Venta Directa": null,
      "Gas": "Gases licuados C02.",
      "Texto Presion 1": "Presión Entrada:",
      "Presion 1": 100,
      "Unidades Presion 1": "Bar",
      "Texto Presion 2": "Presión Salida:",
      "Presion 2": " 2 - 14",
      "Unidades Presion 2": "Bar",
      "Texto Caudal (N\")": "Caudal:",
      "Caudal (N2)": 15,
      "Unidades Caudal (N2)": "Nm3/h",
      "Material Cuerpo": "Latón",
      "Regulador Tipo": "Membrana Inoxidable",
      "Material Cierre": "Teflón",
      "Material Junta": "Nitrilo",
      "Material Asiento": null,
      "Material Fuelle": null,
      "Material Eje": null,
      "Material Husillo": null,
      "Material Bola": null,
      "Material Tubo": null,
      "Orificio": null,
      "Unidades Orificio": null,
      "Conexion Entrada": null,
      "Conexion Salida": null,
      "Tipo conexion entrada Botella": null,
      "Conexion valvula": null,
      "Conexion rampa": null,
      "Dist. entre tomas": null,
      "Unidades Dist. entre tomas": null,
      "Dist. entre soportes": null,
      "Unidades Dist. entre soportes": null,
      "Material colector": null,
      "Diametro Exterior": null,
      "Unidades Diametro Exterior": null,
      "Conexion a Botella": null,
      "Rosca-Espiga": null,
      "Material Caña": null,
      "Material Tuerca": null,
      "Campo de ajuste": null,
      "Unidades Campo de ajuste": null,
      "Clasificacion Proteccion": null,
      "Resistencia": null,
      "Unidades Resistencia": null,
      "Contenedor": null,
      "Unidades Contenedor": null,
      "Diametro Contenedor": null,
      "Superficie Activa": null,
      "Termostato": null,
      "Peso Pallet": null,
      "Unidades Peso Pallet": null,
      "Tamaño Pallet": null,
      "Tiempo de inyeccion": null,
      "Unidades Tiempo de inyeccion": null,
      "Tipo de Globo": null,
      "Unnamed: 72": null,
      "Unnamed: 73": null,
      "Complementos": null,
      "Tipo de Entrada": null,
      "Conexion Entrada.1": null,
      "Conexion Salida.1": null,
      "Conexion Valvula": null,
      "Conexion Rampa": null,
      "Dist. Entre tomas": null,
      "Presion de trabajo": null,
      "Dist. Entre Soportes": null,
      "Diametro Interior": null,
      "Conexion": null,
      "Orificio.1": null,
      "Presion Max.": null,
      "Presion Tarado": null,
      "Campo de Ajuste": null,
      "Longitud cable salida": null,
      "Rango de Presion": null,
      "Proteccion Clasificacion": null,
      "Presion Nominal": null,
      "Peso Pallet.1": null,
      "Tamaño Pallet.1": null,
      "Tiempo de inyección": null,
      "Conexion a botella": null,
      "Naprox de Pallet x 6,35 kg CO2": null,
      "Composicion": null,
      "Tipo de Globo.1": null,
      "Tipo de Conexion": null,
      "Tipo": null,
      "Junta": null,
      "Conexion a Regulador": null,
      "Material Caña ": null,
      "Material Tuerca.1": null,
      "Capacidad geometrica litros": null,
      "Capacidad de gas aprox": null,
      "Peso Total": null
    },
    {
      "Negocio": "Packaged",
      "Categoria de Gas": "Gases Especiales",
      "Categorias": "Paneles Gases Especiales (200 Bar)",
      "Sub-Categoria": null,
      "Sub-Categoria 2": null,
      "Forma de suministro": null,
      "Etapa": null,
      "Tipo de Gas": null,
      "Modelo": "Paneles de regulación IGE-10",
      "Unnamed: 9": null,
      "Nombre": "IGE-10/200/14",
      "Texto Codigo": "Cod.",
      "Codigo": 81249,
      "Texto Codigo 2": null,
      "Codigo Purga": null,
      "Texto Codigo 3": null,
      "Codigo 3": null,
      "Venta Directa": null,
      "Gas": "Gases comprimidos NO corrosivos (N2/O2/H2/Ar/He/Aire/etc.) Válido N2O.",
      "Texto Presion 1": "Presión Entrada:",
      "Presion 1": 200,
      "Unidades Presion 1": "Bar",
      "Texto Presion 2": "Presión Salida:",
      "Presion 2": " 2 - 14",
      "Unidades Presion 2": "Bar",
      "Texto Caudal (N\")": "Caudal:",
      "Caudal (N2)": 20,
      "Unidades Caudal (N2)": "Nm3/h",
      "Material Cuerpo": "Latón",
      "Regulador Tipo": "Membrana Inoxidable",
      "Material Cierre": "Teflón",
      "Material Junta": "Vitón",
      "Material Asiento": null,
      "Material Fuelle": null,
      "Material Eje": null,
      "Material Husillo": null,
      "Material Bola": null,
      "Material Tubo": null,
      "Orificio": null,
      "Unidades Orificio": null,
      "Conexion Entrada": null,
      "Conexion Salida": null,
      "Tipo conexion entrada Botella": null,
      "Conexion valvula": null,
      "Conexion rampa": null,
      "Dist. entre tomas": null,
      "Unidades Dist. entre tomas": null,
      "Dist. entre soportes": null,
      "Unidades Dist. entre soportes": null,
      "Material colector": null,
      "Diametro Exterior": null,
      "Unidades Diametro Exterior": null,
      "Conexion a Botella": null,
      "Rosca-Espiga": null,
      "Material Caña": null,
      "Material Tuerca": null,
      "Campo de ajuste": null,
      "Unidades Campo de ajuste": null,
      "Clasificacion Proteccion": null,
      "Resistencia": null,
      "Unidades Resistencia": null,
      "Contenedor": null,
      "Unidades Contenedor": null,
      "Diametro Contenedor": null,
      "Superficie Activa": null,
      "Termostato": null,
      "Peso Pallet": null,
      "Unidades Peso Pallet": null,
      "Tamaño Pallet": null,
      "Tiempo de inyeccion": null,
      "Unidades Tiempo de inyeccion": null,
      "Tipo de Globo": null,
      "Unnamed: 72": null,
      "Unnamed: 73": null,
      "Complementos": null,
      "Tipo de Entrada": null,
      "Conexion Entrada.1": null,
      "Conexion Salida.1": null,
      "Conexion Valvula": null,
      "Conexion Rampa": null,
      "Dist. Entre tomas": null,
      "Presion de trabajo": null,
      "Dist. Entre Soportes": null,
      "Diametro Interior": null,
      "Conexion": null,
      "Orificio.1": null,
      "Presion Max.": null,
      "Presion Tarado": null,
      "Campo de Ajuste": null,
      "Longitud cable salida": null,
      "Rango de Presion": null,
      "Proteccion Clasificacion": null,
      "Presion Nominal": null,
      "Peso Pallet.1": null,
      "Tamaño Pallet.1": null,
      "Tiempo de inyección": null,
      "Conexion a botella": null,
      "Naprox de Pallet x 6,35 kg CO2": null,
      "Composicion": null,
      "Tipo de Globo.1": null,
      "Tipo de Conexion": null,
      "Tipo": null,
      "Junta": null,
      "Conexion a Regulador": null,
      "Material Caña ": null,
      "Material Tuerca.1": null,
      "Capacidad geometrica litros": null,
      "Capacidad de gas aprox": null,
      "Peso Total": null
    },
    {
      "Negocio": "Packaged",
      "Categoria de Gas": "Gases Especiales",
      "Categorias": "Paneles Gases Especiales (200 Bar)",
      "Sub-Categoria": null,
      "Sub-Categoria 2": null,
      "Forma de suministro": null,
      "Etapa": null,
      "Tipo de Gas": null,
      "Modelo": "Paneles de regulación IGE-10",
      "Unnamed: 9": null,
      "Nombre": "IGE-10/200/35",
      "Texto Codigo": "Cod.",
      "Codigo": 81250,
      "Texto Codigo 2": null,
      "Codigo Purga": null,
      "Texto Codigo 3": null,
      "Codigo 3": null,
      "Venta Directa": null,
      "Gas": "Gases comprimidos NO corrosivos (N2/O2/H2/Ar/He/Aire/etc.) Válido N2O.",
      "Texto Presion 1": "Presión Entrada:",
      "Presion 1": 200,
      "Unidades Presion 1": "Bar",
      "Texto Presion 2": "Presión Salida:",
      "Presion 2": " 5 - 35",
      "Unidades Presion 2": "Bar",
      "Texto Caudal (N\")": "Caudal:",
      "Caudal (N2)": 30,
      "Unidades Caudal (N2)": "Nm3/h",
      "Material Cuerpo": "Latón",
      "Regulador Tipo": "Membrana Inoxidable",
      "Material Cierre": "Teflón",
      "Material Junta": "Vitón",
      "Material Asiento": null,
      "Material Fuelle": null,
      "Material Eje": null,
      "Material Husillo": null,
      "Material Bola": null,
      "Material Tubo": null,
      "Orificio": null,
      "Unidades Orificio": null,
      "Conexion Entrada": null,
      "Conexion Salida": null,
      "Tipo conexion entrada Botella": null,
      "Conexion valvula": null,
      "Conexion rampa": null,
      "Dist. entre tomas": null,
      "Unidades Dist. entre tomas": null,
      "Dist. entre soportes": null,
      "Unidades Dist. entre soportes": null,
      "Material colector": null,
      "Diametro Exterior": null,
      "Unidades Diametro Exterior": null,
      "Conexion a Botella": null,
      "Rosca-Espiga": null,
      "Material Caña": null,
      "Material Tuerca": null,
      "Campo de ajuste": null,
      "Unidades Campo de ajuste": null,
      "Clasificacion Proteccion": null,
      "Resistencia": null,
      "Unidades Resistencia": null,
      "Contenedor": null,
      "Unidades Contenedor": null,
      "Diametro Contenedor": null,
      "Superficie Activa": null,
      "Termostato": null,
      "Peso Pallet": null,
      "Unidades Peso Pallet": null,
      "Tamaño Pallet": null,
      "Tiempo de inyeccion": null,
      "Unidades Tiempo de inyeccion": null,
      "Tipo de Globo": null,
      "Unnamed: 72": null,
      "Unnamed: 73": null,
      "Complementos": null,
      "Tipo de Entrada": null,
      "Conexion Entrada.1": null,
      "Conexion Salida.1": null,
      "Conexion Valvula": null,
      "Conexion Rampa": null,
      "Dist. Entre tomas": null,
      "Presion de trabajo": null,
      "Dist. Entre Soportes": null,
      "Diametro Interior": null,
      "Conexion": null,
      "Orificio.1": null,
      "Presion Max.": null,
      "Presion Tarado": null,
      "Campo de Ajuste": null,
      "Longitud cable salida": null,
      "Rango de Presion": null,
      "Proteccion Clasificacion": null,
      "Presion Nominal": null,
      "Peso Pallet.1": null,
      "Tamaño Pallet.1": null,
      "Tiempo de inyección": null,
      "Conexion a botella": null,
      "Naprox de Pallet x 6,35 kg CO2": null,
      "Composicion": null,
      "Tipo de Globo.1": null,
      "Tipo de Conexion": null,
      "Tipo": null,
      "Junta": null,
      "Conexion a Regulador": null,
      "Material Caña ": null,
      "Material Tuerca.1": null,
      "Capacidad geometrica litros": null,
      "Capacidad de gas aprox": null,
      "Peso Total": null
    }
  ];

  constructor() { }

  getMaterial(){
    return this.myMaterial;
  }
}
