import { Injectable } from '@angular/core';
import { Material } from '../models/material.model';
import { DATA } from '../../assets/data/data06022022'

@Injectable({
  providedIn: 'root'
})
export class MaterialService {

  private myMaterial : Material[]=[
    // {
    //     "Negocio": "Packaged",
    //     "Categoria_Gas": "Gases Especiales",
    //     "Categorias": "Paneles Gases Especiales (200 Bar)",
    //     "Sub_Categoria": null,
    //     "Sub_Categoria_2": null,
    //     "Forma_suministro": null,
    //     "Etapa": null,
    //     "Tipo_Gas": null,
    //     "Modelo": "Paneles de regulación IGE-10",
    //     "Nombre": "IGE-10/40/1.5",
    //     "Texto_Codigo": "Cod.",
    //     "Codigo": 81248,
    //     "Texto_Codigo_2": null,
    //     "Codigo_Purga": null,
    //     "Texto_Codigo_3": null,
    //     "Codigo_3": null,
    //     "Venta_Directa": null,
    //     "Gas": "Acetileno y gases omprimidos NO corrosivos.",
    //     "Texto_Presion_1": "Presión Entrada:",
    //     "Presion_1": 40,
    //     "Unidades_Presion_1": "Bar",
    //     "Texto_Presion_2": "Presión Salida:",
    //     "Presion_2": "0,2 - 1,5",
    //     "Unidades_Presion_2": "Bar",
    //     "Texto_Caudal_N": "Caudal:",
    //     "Caudal_N2": 5,
    //     "Unidades_Caudal_N2": "Nm3/h",
    //     "Material_Cuerpo": "Latón",
    //     "Regulador_Tipo": "Membrana Inoxidable",
    //     "Material_Cierre": "Teflón",
    //     "Material_Junta": "EPDM",
    //     "Material_Asiento": null,
    //     "Material_Fuelle": null,
    //     "MateriaL_Eje": null,
    //     "Material_Husillo": null,
    //     "Material_Bola": null,
    //     "Material_Tubo": null,
    //     "Orificio": null,
    //     "Unidades_Orificio": null,
    //     "Conexión_Entrada": null,
    //     "Conexión_Salida": null,
    //     "Tipo_conexion_entrada_Botella": null,
    //     "Conexión_valvula": null,
    //     "Conexion_rampa": null,
    //     "Dist_entre_tomas": null,
    //     "Unidades_Dist_entre_tomas": null,
    //     "Dist_entre_soportes": null,
    //     "Unidades_Dist_entre_soportes": null,
    //     "Material_colector": null,
    //     "Diametro_Exterior": null,
    //     "Unidades_Diametro_Exterior": null,
    //     "Conexión_Botella": null,
    //     "Rosca_Espiga": null,
    //     "Material_Caña": null,
    //     "Material_Tuerca": null,
    //     "Campo_de_ajuste": null,
    //     "Unidades_Campo_de_ajuste": null,
    //     "Clasificacion_Proteccion": null,
    //     "Resistencia": null,
    //     "Unidades_Resistencia": null,
    //     "Contenedor": null,
    //     "Unidades_Contenedor": null,
    //     "Diametro_Contenedor": null,
    //     "Superficie_Activa": null,
    //     "Termostato": null,
    //     "Peso_Pallet": null,
    //     "Unidades_Peso_Pallet": null,
    //     "Tamaño_Pallet": null,
    //     "Tiempo_de_inyeccion": null,
    //     "Unidades_Tiempo_de_inyeccion": null,
    //     "Tipo_de_Globo": null
    //   },
    //   {
    //     "Negocio": "Packaged",
    //     "Categoria_Gas": "Gases Especiales",
    //     "Categorias": "Paneles Gases Especiales (200 Bar)",
    //     "Sub_Categoria": null,
    //     "Sub_Categoria_2": null,
    //     "Forma_suministro": null,
    //     "Etapa": null,
    //     "Tipo_Gas": null,
    //     "Modelo": "Paneles de regulación IGE-10",
    //     "Nombre": "IGE-10/100/14",
    //     "Texto_Codigo": "Cod.",
    //     "Codigo": 81265,
    //     "Texto_Codigo_2": null,
    //     "Codigo_Purga": null,
    //     "Texto_Codigo_3": null,
    //     "Codigo_3": null,
    //     "Venta_Directa": null,
    //     "Gas": "Gases licuados C02.",
    //     "Texto_Presion_1": "Presión Entrada:",
    //     "Presion_1": 100,
    //     "Unidades_Presion_1": "Bar",
    //     "Texto_Presion_2": "Presión Salida:",
    //     "Presion_2": " 2 - 14",
    //     "Unidades_Presion_2": "Bar",
    //     "Texto_Caudal_N": "Caudal:",
    //     "Caudal_N2": 15,
    //     "Unidades_Caudal_N2": "Nm3/h",
    //     "Material_Cuerpo": "Latón",
    //     "Regulador_Tipo": "Membrana Inoxidable",
    //     "Material_Cierre": "Teflón",
    //     "Material_Junta": "Nitrilo",
    //     "Material_Asiento": null,
    //     "Material_Fuelle": null,
    //     "MateriaL_Eje": null,
    //     "Material_Husillo": null,
    //     "Material_Bola": null,
    //     "Material_Tubo": null,
    //     "Orificio": null,
    //     "Unidades_Orificio": null,
    //     "Conexión_Entrada": null,
    //     "Conexión_Salida": null,
    //     "Tipo_conexion_entrada_Botella": null,
    //     "Conexión_valvula": null,
    //     "Conexion_rampa": null,
    //     "Dist_entre_tomas": null,
    //     "Unidades_Dist_entre_tomas": null,
    //     "Dist_entre_soportes": null,
    //     "Unidades_Dist_entre_soportes": null,
    //     "Material_colector": null,
    //     "Diametro_Exterior": null,
    //     "Unidades_Diametro_Exterior": null,
    //     "Conexión_Botella": null,
    //     "Rosca_Espiga": null,
    //     "Material_Caña": null,
    //     "Material_Tuerca": null,
    //     "Campo_de_ajuste": null,
    //     "Unidades_Campo_de_ajuste": null,
    //     "Clasificacion_Proteccion": null,
    //     "Resistencia": null,
    //     "Unidades_Resistencia": null,
    //     "Contenedor": null,
    //     "Unidades_Contenedor": null,
    //     "Diametro_Contenedor": null,
    //     "Superficie_Activa": null,
    //     "Termostato": null,
    //     "Peso_Pallet": null,
    //     "Unidades_Peso_Pallet": null,
    //     "Tamaño_Pallet": null,
    //     "Tiempo_de_inyeccion": null,
    //     "Unidades_Tiempo_de_inyeccion": null,
    //     "Tipo_de_Globo": null
    //   },
    //   {
    //     "Negocio": "Packaged",
    //     "Categoria_Gas": "Gases Especiales",
    //     "Categorias": "Paneles Gases Especiales (200 Bar)",
    //     "Sub_Categoria": null,
    //     "Sub_Categoria_2": null,
    //     "Forma_suministro": null,
    //     "Etapa": null,
    //     "Tipo_Gas": null,
    //     "Modelo": "Paneles de regulación IGE-10",
    //     "Nombre": "IGE-10/200/14",
    //     "Texto_Codigo": "Cod.",
    //     "Codigo": 81249,
    //     "Texto_Codigo_2": null,
    //     "Codigo_Purga": null,
    //     "Texto_Codigo_3": null,
    //     "Codigo_3": null,
    //     "Venta_Directa": null,
    //     "Gas": "Gases comprimidos NO corrosivos (N2/O2/H2/Ar/He/Aire/etc.) Válido N2O.",
    //     "Texto_Presion_1": "Presión Entrada:",
    //     "Presion_1": 200,
    //     "Unidades_Presion_1": "Bar",
    //     "Texto_Presion_2": "Presión Salida:",
    //     "Presion_2": " 2 - 14",
    //     "Unidades_Presion_2": "Bar",
    //     "Texto_Caudal_N": "Caudal:",
    //     "Caudal_N2": 20,
    //     "Unidades_Caudal_N2": "Nm3/h",
    //     "Material_Cuerpo": "Latón",
    //     "Regulador_Tipo": "Membrana Inoxidable",
    //     "Material_Cierre": "Teflón",
    //     "Material_Junta": "Vitón",
    //     "Material_Asiento": null,
    //     "Material_Fuelle": null,
    //     "MateriaL_Eje": null,
    //     "Material_Husillo": null,
    //     "Material_Bola": null,
    //     "Material_Tubo": null,
    //     "Orificio": null,
    //     "Unidades_Orificio": null,
    //     "Conexión_Entrada": null,
    //     "Conexión_Salida": null,
    //     "Tipo_conexion_entrada_Botella": null,
    //     "Conexión_valvula": null,
    //     "Conexion_rampa": null,
    //     "Dist_entre_tomas": null,
    //     "Unidades_Dist_entre_tomas": null,
    //     "Dist_entre_soportes": null,
    //     "Unidades_Dist_entre_soportes": null,
    //     "Material_colector": null,
    //     "Diametro_Exterior": null,
    //     "Unidades_Diametro_Exterior": null,
    //     "Conexión_Botella": null,
    //     "Rosca_Espiga": null,
    //     "Material_Caña": null,
    //     "Material_Tuerca": null,
    //     "Campo_de_ajuste": null,
    //     "Unidades_Campo_de_ajuste": null,
    //     "Clasificacion_Proteccion": null,
    //     "Resistencia": null,
    //     "Unidades_Resistencia": null,
    //     "Contenedor": null,
    //     "Unidades_Contenedor": null,
    //     "Diametro_Contenedor": null,
    //     "Superficie_Activa": null,
    //     "Termostato": null,
    //     "Peso_Pallet": null,
    //     "Unidades_Peso_Pallet": null,
    //     "Tamaño_Pallet": null,
    //     "Tiempo_de_inyeccion": null,
    //     "Unidades_Tiempo_de_inyeccion": null,
    //     "Tipo_de_Globo": null
    //   },
    //   {
    //     "Negocio": "Packaged",
    //     "Categoria_Gas": "Gases Especiales",
    //     "Categorias": "Paneles Gases Especiales (200 Bar)",
    //     "Sub_Categoria": null,
    //     "Sub_Categoria_2": null,
    //     "Forma_suministro": null,
    //     "Etapa": null,
    //     "Tipo_Gas": null,
    //     "Modelo": "Paneles de regulación IGE-10",
    //     "Nombre": "IGE-10/200/35",
    //     "Texto_Codigo": "Cod.",
    //     "Codigo": 81250,
    //     "Texto_Codigo_2": null,
    //     "Codigo_Purga": null,
    //     "Texto_Codigo_3": null,
    //     "Codigo_3": null,
    //     "Venta_Directa": null,
    //     "Gas": "Gases comprimidos NO corrosivos (N2/O2/H2/Ar/He/Aire/etc.) Válido N2O.",
    //     "Texto_Presion_1": "Presión Entrada:",
    //     "Presion_1": 200,
    //     "Unidades_Presion_1": "Bar",
    //     "Texto_Presion_2": "Presión Salida:",
    //     "Presion_2": " 5 - 35",
    //     "Unidades_Presion_2": "Bar",
    //     "Texto_Caudal_N": "Caudal:",
    //     "Caudal_N2": 30,
    //     "Unidades_Caudal_N2": "Nm3/h",
    //     "Material_Cuerpo": "Latón",
    //     "Regulador_Tipo": "Membrana Inoxidable",
    //     "Material_Cierre": "Teflón",
    //     "Material_Junta": "Vitón",
    //     "Material_Asiento": null,
    //     "Material_Fuelle": null,
    //     "MateriaL_Eje": null,
    //     "Material_Husillo": null,
    //     "Material_Bola": null,
    //     "Material_Tubo": null,
    //     "Orificio": null,
    //     "Unidades_Orificio": null,
    //     "Conexión_Entrada": null,
    //     "Conexión_Salida": null,
    //     "Tipo_conexion_entrada_Botella": null,
    //     "Conexión_valvula": null,
    //     "Conexion_rampa": null,
    //     "Dist_entre_tomas": null,
    //     "Unidades_Dist_entre_tomas": null,
    //     "Dist_entre_soportes": null,
    //     "Unidades_Dist_entre_soportes": null,
    //     "Material_colector": null,
    //     "Diametro_Exterior": null,
    //     "Unidades_Diametro_Exterior": null,
    //     "Conexión_Botella": null,
    //     "Rosca_Espiga": null,
    //     "Material_Caña": null,
    //     "Material_Tuerca": null,
    //     "Campo_de_ajuste": null,
    //     "Unidades_Campo_de_ajuste": null,
    //     "Clasificacion_Proteccion": null,
    //     "Resistencia": null,
    //     "Unidades_Resistencia": null,
    //     "Contenedor": null,
    //     "Unidades_Contenedor": null,
    //     "Diametro_Contenedor": null,
    //     "Superficie_Activa": null,
    //     "Termostato": null,
    //     "Peso_Pallet": null,
    //     "Unidades_Peso_Pallet": null,
    //     "Tamaño_Pallet": null,
    //     "Tiempo_de_inyeccion": null,
    //     "Unidades_Tiempo_de_inyeccion": null,
    //     "Tipo_de_Globo": null
    //   },
    //   {
    //     "Negocio": "Packaged",
    //     "Categoria_Gas": "Gases Especiales",
    //     "Categorias": "Paneles Gases Especiales (200 Bar)",
    //     "Sub_Categoria": null,
    //     "Sub_Categoria_2": null,
    //     "Forma_suministro": null,
    //     "Etapa": null,
    //     "Tipo_Gas": null,
    //     "Modelo": "Paneles de regulación IGE-11",
    //     "Nombre": "IGE-11/40",
    //     "Texto_Codigo": "Cod.",
    //     "Codigo": 81277,
    //     "Texto_Codigo_2": null,
    //     "Codigo_Purga": null,
    //     "Texto_Codigo_3": null,
    //     "Codigo_3": null,
    //     "Venta_Directa": null,
    //     "Gas": "Acetileno y gases omprimidos NO corrosivos.",
    //     "Texto_Presion_1": "Presión Entrada:",
    //     "Presion_1": 40,
    //     "Unidades_Presion_1": "Bar",
    //     "Texto_Presion_2": "-",
    //     "Presion_2": "-",
    //     "Unidades_Presion_2": "-",
    //     "Texto_Caudal_N": "-",
    //     "Caudal_N2": 0,
    //     "Unidades_Caudal_N2": "-",
    //     "Material_Cuerpo": "Latón",
    //     "Regulador_Tipo": "-",
    //     "Material_Cierre": "-",
    //     "Material_Junta": "EPDM",
    //     "Material_Asiento": null,
    //     "Material_Fuelle": null,
    //     "MateriaL_Eje": null,
    //     "Material_Husillo": null,
    //     "Material_Bola": null,
    //     "Material_Tubo": null,
    //     "Orificio": null,
    //     "Unidades_Orificio": null,
    //     "Conexión_Entrada": null,
    //     "Conexión_Salida": null,
    //     "Tipo_conexion_entrada_Botella": null,
    //     "Conexión_valvula": null,
    //     "Conexion_rampa": null,
    //     "Dist_entre_tomas": null,
    //     "Unidades_Dist_entre_tomas": null,
    //     "Dist_entre_soportes": null,
    //     "Unidades_Dist_entre_soportes": null,
    //     "Material_colector": null,
    //     "Diametro_Exterior": null,
    //     "Unidades_Diametro_Exterior": null,
    //     "Conexión_Botella": null,
    //     "Rosca_Espiga": null,
    //     "Material_Caña": null,
    //     "Material_Tuerca": null,
    //     "Campo_de_ajuste": null,
    //     "Unidades_Campo_de_ajuste": null,
    //     "Clasificacion_Proteccion": null,
    //     "Resistencia": null,
    //     "Unidades_Resistencia": null,
    //     "Contenedor": null,
    //     "Unidades_Contenedor": null,
    //     "Diametro_Contenedor": null,
    //     "Superficie_Activa": null,
    //     "Termostato": null,
    //     "Peso_Pallet": null,
    //     "Unidades_Peso_Pallet": null,
    //     "Tamaño_Pallet": null,
    //     "Tiempo_de_inyeccion": null,
    //     "Unidades_Tiempo_de_inyeccion": null,
    //     "Tipo_de_Globo": null
    //   }
  ];

  constructor() { }

  getMaterial(){
    return DATA;
    // return this.myMaterial;
  }
}
